### ISSUE TITLE
[ BUG ] 이미지 업로드 시 최대 용량 제한 때문에 오류

### ISSUE THREAD

**Issue by yeonjue-2** [teawan-Noh/eventcafecloud#116]
## 🥝 작업 내용

- [x] 에러 사항
- [ ] 변경 사항
- [ ] 요청 사항

## 🌽 작업 설명

- 이미지 업로드 시 최대 용량 제한 때문에 용량 초과 파일을 업로드 시 오류 뜸

**Comment by teawan-Noh** [comment]
https://ncodingdiary.tistory.com/396

**Comment by yeonjue-2** [comment]
yml에 maxFile, maxRequest 를 추가 해줌으로써 오류 해결 

spring:
servlet:
    multipart:
      maxFileSize : 3MB
      maxRequestSize : 12MB
