### ISSUE TITLE
[ BUG ] 구글 소셜 로그인시 도메인 분리 현상

### ISSUE THREAD

**Issue by teawan-Noh** [teawan-Noh/eventcafecloud#135]
## 🥝 작업 내용

- [x] 에러 사항
- [ ] 변경 사항
- [ ] 요청 사항

## 🌽 작업 설명

- 구글 소셜 로그인시 도메인 분리 현상 발생 
- www.eventcafecloud.com와 eventcafecloud.com가 서로 다른 주소로 작동하여 각각의 사이트에서 로그인이 됨

**Comment by nnakki** [comment]
구글의 경우 소셜 로그인시 www.eventcafecloud.com 과 eventcafecloud.com을 리다이렉트 시 같은 도메인으로 인식하지 못했습니다. 
때문에 사이트 로그인 시, 쿠키에 심어지는 도메인을 동일하게 저희 서버에서 작업해줄 필요가 있었습니다. 
쿠키에 토큰을 심을 때, cookie.setDomain 함수를 사용하여 저희 서버의 도메인을 직접 쿠키에 입력해 어떤 경로로 접속하든 쿠키에 같은 도메인을 받을 수 있도록 설정해주었습니다. 

![image](https://user-images.githubusercontent.com/93200574/179943914-a9722caa-2d18-40a7-810e-b9b2562e072e.png)
