### ISSUE TITLE
[ Enhancement ] url로 다른 유저의 게시글(Cafe, Post)에 대한 api 요청시 진행되는 문제  

### ISSUE THREAD

**Issue by teawan-Noh** [teawan-Noh/eventcafecloud#141]
## 🥝 작업 내용

- [ ] 에러 사항
- [ ] 변경 사항
- [x] 요청 사항

## 🌽 작업 설명

- url로 다른 유저의 게시글(Cafe, post)에 대한 api 요청시 진행되는 문제 방지 
- 요청을 보낸유저(로그인한 유저)와 해당 게시글의 작성자가 다를 경우 에러 페이지를 반환하도록 처리!

**Comment by teawan-Noh** [comment]
카페 완료 되었습니다

**Comment by aichyu312** [comment]
게시판도 수정 완료했습니다!
