### ISSUE TITLE
[ BUG ] 지연로딩 이후, 초기화가 안되는 문제 

### ISSUE THREAD

**Issue by nnakki** [teawan-Noh/eventcafecloud#151]
## 🥝 작업 내용

- [x] 에러 사항
- [ ] 변경 사항
- [ ] 요청 사항

## 🌽 작업 설명
![image](https://user-images.githubusercontent.com/93200574/181173090-a0f19772-aa01-45ee-80aa-df9969bfaca4.png)

북마크 레포지토리를 통해, 북마크 저장 된 카페 정보를 불러오는 과정에서 
카페 정보가 모두 null 값으로 불러와집니다. 
FetchType이 Lazy가 아니면 값이 제대로 불러와지는 걸로 보아, 지연로딩 이후 초기화가 안되는 문제라고 생각됩니다.

**Comment by teawan-Noh** [comment]
영속성 컨텍스트의 생존범위 문제로 OSIV 관련 자료 참조.
참고 블로그 : https://catsbi.oopy.io/eedf92ff-8834-458d-86e4-0ed2e01b5971

Entity를 dto로 변환시 영속성 컨텍스트가 끊기면서 문제 해결
#156 참조
