### ISSUE TITLE
🔻메소드 명명 규칙🔻

### ISSUE THREAD

**Issue by nnakki** [teawan-Noh/eventcafecloud#17]
## 🥝 작업 내용

- [ ] 에러 사항
- [ ] 변경 사항
- [x] 요청 사항

## 🌽 작업 설명

- 새로운 튜터님들과도 얘기해보고, 형철튜터님에게도 궁금해져서 여쭤봤던 사항인데 메소드명에 대한 명명규칙을 정하는 건 어떨까 합니다! :>
- Controller쪽에서는 메소드명을 CRUD의 형태에 가깝게 (create~, update~, delete~)라고 구현을 한다고 하시고
- Service쪽에서는 메소드명을 DB의 형태에 가깝게 (save~, modify~, remove~, find~)라는 형태로 구현을 한다고 합니다!
ex) AdminController
![image](https://user-images.githubusercontent.com/93200574/177292082-f65cd7be-d857-4a29-8441-f1eeb30fec89.png)
튜터님이 알려주신대로 컨트롤러에서 최종적으로 담기는 모습은 update, service에서 사용된 메소드는 modify로 명명했습니다! 
굳이! 신경써서 지킬 필요까지는 없다고 하지만, 그래도 통일감이 있으면 좋고, 저희는 개발 초반이기도 하니까 다같이 명명규칙을 맞춰보는 건 어떨까합니다 :>

**Comment by teawan-Noh** [comment]
controller에서의 이름과 service에서의 이름이 다르네요??

**Comment by yeonjue-2** [comment]
다같이 정해보면 좋을 것 같습니다!

**Comment by aichyu312** [comment]
좋습니다 ! 우선위의 예시 메소드명 여덟개는 천천히 수정하면서 작성해보겠습니다~~
