### ISSUE TITLE
s3 엑세스 토큰 깃허브에 올리지 말아주세요...

### ISSUE THREAD

**Issue by teawan-Noh** [teawan-Noh/eventcafecloud#19]
## 🥝 작업 내용

- [x] 에러 사항
- [ ] 변경 사항
- [x] 요청 사항

## 🌽 작업 설명

- 엑세스 토큰이 깃허브에 올라와서 경고 먹었어요... 토큰 지우고 다시 만들어야합니다 ㅠㅠ

**Comment by nnakki** [comment]
넵... 죄송합니다... 사랑합니다 팀장님... 🫶🏻
