### ISSUE TITLE
[ BUG ] ajax로 url 호출 ->  400에러 발생

### ISSUE THREAD

**Issue by teawan-Noh** [teawan-Noh/eventcafecloud#21]
## 🥝 작업 내용

- [x] 에러 사항
- [ ] 변경 사항
- [x] 요청 사항

## 🌽 작업 설명
접근 요청 api url : /api/v1/cafes
카페 List 호출을 ajax를 이용하여 비동기 방식으로 구현하려 함.
-> 호출하려는 api 사용을 허가하기 위해 SecurityConfig 파일에 .antMatchers("/api/**").permitAll() 추가 

-> 400 에러가 발생 : 잘못된 요청으로써 문법상 오류가 있어서 서버가 요청사항을 이해하지 못하는 경우

예지님 help
-

**Comment by nnakki** [comment]
인증 / 인가에 관련되서 나오는 Error는 401 / 403 이 아닌가 싶은데..!! 400은 주로 클라이언트 요청이 잘못됨(구문이 잘못됨)등으로 발생하는 건 아닌가 합니다! 오타가 있거나, data요청에 잘못된 부분이 없는지 한번 더 확인해주시구, 저도 내일 일어나서 확인해보겠습니다 👏🏻

**Comment by teawan-Noh** [comment]
controller에서 매개변수로 @RequestParam("page")을 받아오는 코드를 작성하였으나 실제로 값을 안넣어준 상태로 서버 내부에서 임의 값을 넣어 테스트 중이었습니다.

@RequestParam이 값을 안보내주면 null이 들어가는 줄 알았는데 @RequestParam의 default가 값이 필수였습니다
그래서 값을 안받아오니 잘못된 데이터를 보냈다고 400을 띄운거였습니다
