### ISSUE TITLE
[ BUG ] TOKEN의 만료시간과, Cookie의 만료시간이 상이함

### ISSUE THREAD

**Issue by nnakki** [teawan-Noh/eventcafecloud#29]
## 🥝 작업 내용

- [x] 에러 사항
- [ ] 변경 사항
- [x] 요청 사항

## 🌽 작업 설명

JWT Token을 쿠키에 담아서 사용하고 있는데, access_token의 실제 만료시간보다 
Cookie에 담긴 access_token의 만료시간이 길어서, 로그인을 하고 시간이 지나면 로그아웃이 되는 게 아니라
'JWT 토큰이 만료됐다'는 에러가 뜨고 있습니다. 수정하겠습니다 T^T

**Comment by aichyu312** [comment]
네네 부탁드리겠습니다 >.< 화이팅팅~

**Comment by nnakki** [comment]
JWT TOKEN에는 Expiry를 저장할때 DATE함수를 사용하여 app.propertie에 미리 설정해놓은 만료시간인 1800000을 밀리세컨으로 인식해서 Token의 만료시간은 30분으로 설정되었었는데, Cookie에 저장할 때는 18000000을 밀리세컨이 아닌 세컨으로 인식해서 시간이 과하게 길었습니다. 단위를 맞춰주기 위해 1000을 나누어서 시간을 동일하게 설정했씁니다 :>
