### ISSUE TITLE
[ BUG ] @Secured("ROLE_HOST")가 인식이 안되는 오류

### ISSUE THREAD

**Issue by nnakki** [teawan-Noh/eventcafecloud#36]
## 🥝 작업 내용

- [x] #38
- [ ] 변경 사항
- [ ] 요청 사항

## 🌽 작업 설명

@Secured("ROLE_HOST")를 설정했을 때 권한이 HOST인 유저도 인식을 못하고, 접근 권한이 막히는 오류 발생

**Comment by aichyu312** [comment]
13분만에 수정이 되었군요 !! 크 멋있습니다

**Comment by nnakki** [comment]
권한을 토큰에 저장하는 과정(OAuth2AuthenticationSuccessHandler)에서 함수가 ADMIN 권한이 아니면 모두 NORMAL권한을 저장하도록 설정되어 있었습니다. 함수에 ADMIN이외에 HOST에 관한 항목도 추가로 검사할 수 있게 하여 오류를 해결했씁니다 :>

**Comment by yeonjue-2** [comment]
빠르게 오류를 잡아주셔서 감사합니다.
