### ISSUE TITLE
[ BUG ] S3에서 받아온 URL로 객체 생성후 DB에 저장이 안되는 오류

### ISSUE THREAD

**Issue by yeonjue-2** [teawan-Noh/eventcafecloud#39]
## 🥝 작업 내용

- [x] 에러 사항
- [ ] 변경 사항
- [ ] 요청 사항

## 🌽 작업 설명

- S3에서 받아온 URL로 객체 생성은 되지만 EventImage 는 DB에 저장이 되지 않는 문제

**Comment by yeonjue-2** [comment]
eventImage를 event의 하위 엔티티 처리하는 cascade 을 달아주지 않아서
DB에 들어가지 않았습니다. 
cascade = CascadeType.ALL 를 달아주면 연관관계대로 DB에 저장이됩니다.

**Comment by yeonjue-2** [comment]
<처리 예시>
@OneToMany(mappedBy = "event", cascade = CascadeType.ALL)
    private List<EventImage> eventImages = new ArrayList<>();

**Comment by teawan-Noh** [comment]
👍👍👍👍👍👍👍👍
