### ISSUE TITLE
[ BUG ] 게시글 삭제 시 댓글이 있는 게시글은 삭제가 안되는 에러가 발생했습니다 ..

### ISSUE THREAD

**Issue by aichyu312** [teawan-Noh/eventcafecloud#41]
## 🥝 작업 내용

- [x] 에러 사항
- [ ] 변경 사항
- [ ] 요청 사항

## 🌽 작업 설명

![33322](https://user-images.githubusercontent.com/103922647/178115089-2588b2f6-d8b0-4bd0-a9cb-f0dd3bcd25ff.PNG)

- 기존에 게시글 삭제 기능 구현 성공하였는데, 댓글기능이 추가된 이후  댓글이 달린 게시물 삭제해보니 삭제가 안되는 에러가 있습니다 ㅠㅠ JPA쪽으로 백엔드 구성하려다가 실패하였습니다 ..

**Comment by yeonjue-2** [comment]
#39 제가 작성한 이슈를 참고해보셔도 좋을 것 같습니다.

**Comment by teawan-Noh** [comment]
casecade를 다시면 될 것 같습니다

**Comment by aichyu312** [comment]
와 ㅠㅠ 바로 아래 이슈였는데, 삭제가 안되던가 / 저장이 안되던가의 차이인것같은데.. 공부를 끊임없이 해야겠군요
다들 댓글 감사합니다!
