### ISSUE TITLE
[ share information ] String의 기본 데이터값을 오버했을 경우, 그리고 그의 해결법!

### ISSUE THREAD

**Issue by aichyu312** [teawan-Noh/eventcafecloud#42]
## 🥝 작업 내용

- [x] 에러 사항
- [ ] 변경 사항
- [ ] 요청 사항

## 🌽 작업 설명

-  늦은 새벽 게시판 css 꾸미던중 .. TEXT 로 설정이 안되어있던 DB를 고쳐보려 조금 먼저 검색을 해보았습니다
 간단히 정리해볼테니, 나중에 타입변환이 필요할 경우 이 이슈를 기억해주시면 감사하겠습니다! 다들 화이팅 !

- 상황 설명
 JPA 로 자동 컬럼 생성이 되었는데, String 으로 기본생성을 하게되었습니다 .
 . 게시판 특성상 길거나 복붙을 해야하는 경우가 있는데 .. String 은 기본 255자 미만으로 설정이 되어있고 데이터가 넘어갈경우

이러한 오류메세지를 맞게 됩니다. 

![33322](https://user-images.githubusercontent.com/103922647/178183495-871fb7e9-5bb6-457b-a8d8-a907e9a455c6.PNG)

1. 우선적으로 컬럼을 설정을 해줄수가 있으며 데이터 값은 아래와 같습니다.
![33333333333](https://user-images.githubusercontent.com/103922647/178118415-6d8da894-8496-4199-b7f3-995936d3ea98.PNG)

다만 미리 설정이 안되어있어 DB / 컬럼이 생성된 경우는 !!자동으로 변환되지 않고 !! DB를 삭제 후 재생성 혹은

![444422222222222](https://user-images.githubusercontent.com/103922647/178118398-02cf5adc-d6ba-4b15-86a6-f98ce391667f.PNG)
3. DB에 들어가 테이블 수정을 하게되면 변경이 가능합니다 . 큰 데이터에서 작은 데이터로 갈경우, 실험은 안해보았으나
 마찬가지로 오류가 뜰것으로 예상됩니다 ! 혹은, 변경이 안되거나 ...ㅎㅎ 나중에 꼭 기억해주시면 안부연락 주세요

![33323424](https://user-images.githubusercontent.com/103922647/178118467-176a0b3a-600c-41d4-9a75-a0fa482d37d5.PNG)

**Comment by teawan-Noh** [comment]
좋은 정보네요 코드에 반영하도록 하겠습니다

**Comment by nnakki** [comment]
오 좋은정보 + 세심한 정리 감사합니다 :> 잘봤습니다!

**Comment by yeonjue-2** [comment]
정리까지 깔끔하게!! 감사합니다.
