### ISSUE TITLE
[BUG] 카페등록시, 카페정보를 입력하고 등록버튼을 연타하면 같은 정보로 2-3개의 카페가 연달아 등록됩니다.

### ISSUE THREAD

**Issue by nnakki** [teawan-Noh/eventcafecloud#70]
## 🥝 작업 내용

- [x] 에러 사항
- [ ] 변경 사항
- [x] 요청 사항

## 🌽 작업 설명

- [BUG] 카페등록시, 카페정보를 입력하고 등록버튼을 연타하면 같은 정보로 2-3개의 카페가 연달아 등록됩니다.
- 하핫! 해결 부탁드려요 만능 팀장님 :>
![image](https://user-images.githubusercontent.com/93200574/178916072-2de74f25-9610-4485-a690-77b647c968db.png)

**Comment by aichyu312** [comment]
오잉 ? 어떻게 되는거지요? 어렸을때 폭탄메일전송같은거 처럼 시연을 해보려고해도 똑같이 안되어요 .. 게시판에서도 혹시 같은 문제가 있을까요!?

**Comment by teawan-Noh** [comment]
https://ncodingdiary.tistory.com/390?category=985057
